project_id = "rasmcxfnlovalvbavitb"

[functions.university-signup]
verify_jwt = false

[functions.create-college-account]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.generate-internship-description]
verify_jwt = false

[functions.career-chat]
verify_jwt = false
